---
layout: cv
title: Josef Adams CV
---
# Josef Adams
Student, Accounting Major

<div id="webaddress">
<a href="isaac@applesdofall.org">isaac@applesdofall.org</a>
| <a href="http://en.wikipedia.org/wiki/Isaac_Newton">My wikipedia page</a>
</div>


## Currently

Student at Brigham Young University Idaho

### Specialized in

Laws of motion, gravitation, minting coins, disliking [Robert Hooke](http://en.wikipedia.org/wiki/Robert_Hooke)


### Research interests

Cooling, power series, optics, alchemy, planetary motions, apples.


## Education
Bachelor of Science in Accounting	April. 2024
Brigham Young University–Idaho	Rexburg, ID
•	GPA: 3.22
•	Area of interest: Tax.
•	Student Accounting Society 2021 – Current.
•	Emphasis in Business.
•	Work full time and part time during school.






## Occupation

Experience
E-Commerce Associate	Apr. 2021 – Current
Walmart		Rexburg, ID
•	Perform inventory management for the corporation.                                       Feb. 2020 – Apr. 2021
•	Respond to critical thinking situations promptly to complete customer orders.   Cedar City, UT
•	Address customers in locating products catered to their needs.
•	Begin shifts at 5 am in the morning.

Cashier		Nov. 2019 - Feb. 2020
Walmart		Evanston, WY
•	Responded to an average from 60-100 customers per day.	Apr. 2018 - Feb. 2019
•	Maintained inventory control through customer transactions.	Rexburg, ID
•	Helped other departments recognize issues with products.	Feb. 2018 - Apr. 2018
•	Developed skills to recognize and address problems pertaining to asset protection.	Evanston, WY

Customer Service Manager	Feb. 2019 - Nov. 2019
Walmart		Rexburg, ID
•	Managed a team of 20-50 associates.
•	Controlled internal cash flows and performed audits on individuals.
•	Resolved customer complaints and concerns.	
•	Provided financial services to customers totaling from $50 - $7000.
•	Assessed customers concerns to satisfy their right of return.
•	Oversaw the claims process and inventory control for the company


<!-- ### Footer

Last updated: May 2013 -->